/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppRoot {
    }
    interface CreatePoll {
        "history": RouterHistory;
    }
    interface LandingPage {
    }
    interface OptionsPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface ResultsPage {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCreatePollElement extends Components.CreatePoll, HTMLStencilElement {
    }
    var HTMLCreatePollElement: {
        prototype: HTMLCreatePollElement;
        new (): HTMLCreatePollElement;
    };
    interface HTMLLandingPageElement extends Components.LandingPage, HTMLStencilElement {
    }
    var HTMLLandingPageElement: {
        prototype: HTMLLandingPageElement;
        new (): HTMLLandingPageElement;
    };
    interface HTMLOptionsPageElement extends Components.OptionsPage, HTMLStencilElement {
    }
    var HTMLOptionsPageElement: {
        prototype: HTMLOptionsPageElement;
        new (): HTMLOptionsPageElement;
    };
    interface HTMLResultsPageElement extends Components.ResultsPage, HTMLStencilElement {
    }
    var HTMLResultsPageElement: {
        prototype: HTMLResultsPageElement;
        new (): HTMLResultsPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "create-poll": HTMLCreatePollElement;
        "landing-page": HTMLLandingPageElement;
        "options-page": HTMLOptionsPageElement;
        "results-page": HTMLResultsPageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CreatePoll {
        "history"?: RouterHistory;
    }
    interface LandingPage {
    }
    interface OptionsPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface ResultsPage {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "create-poll": CreatePoll;
        "landing-page": LandingPage;
        "options-page": OptionsPage;
        "results-page": ResultsPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "create-poll": LocalJSX.CreatePoll & JSXBase.HTMLAttributes<HTMLCreatePollElement>;
            "landing-page": LocalJSX.LandingPage & JSXBase.HTMLAttributes<HTMLLandingPageElement>;
            "options-page": LocalJSX.OptionsPage & JSXBase.HTMLAttributes<HTMLOptionsPageElement>;
            "results-page": LocalJSX.ResultsPage & JSXBase.HTMLAttributes<HTMLResultsPageElement>;
        }
    }
}
